
name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs At 10:00 AM and 10:00 PM
    - cron: "0 10,22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UClBC38DugxE0gcaswAm6cXA

